train_file: ['dataset/downstream_json/nlvr_train.json']
val_file: ['dataset/downstream_json/nlvr_dev.json']                  
test_file: ['dataset/downstream_json/nlvr_test.json']  

image_root: '/SHARE_ST/mind/dataset/nlvr2/' 

image_res: 384
batch_size: 16

bert_config: 'configs/config_bert.json'

alpha: 0
distill: False 
warm_up: True
eval_ema: False

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







