train_file:  ['dataset/downstream_json/flickr30k_train.json']
val_file: 'dataset/downstream_json/flickr30k_val.json'                
test_file: 'dataset/downstream_json/flickr30k_test.json'
image_root: '/dataset/flickr30k_images'

bert_config: 'configs/config_bert.json'

image_res: 384
batch_size_train: 64
batch_size_test: 96

queue_size: 65280 
use_momentum: True
momentum: 0.995

vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128

alpha: 0 
distill: False
warm_up: True

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5,  warmup_epochs: 1, cooldown_epochs: 0}







